# Generated by Django 2.2.3 on 2019-07-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(blank=True, max_length=32)),
                ('sha1', models.CharField(blank=True, max_length=40)),
                ('sha256', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
    ]
