# Generated by Django 2.2.3 on 2019-07-25 06:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('z_lab_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='update_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='searchtag',
            name='count',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
