# Generated by Django 2.2.3 on 2019-07-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_lab_engine', '0002_auto_20190725_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtag',
            name='count',
            field=models.IntegerField(),
        ),
    ]
