# Generated by Django 2.2.3 on 2019-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_lab_engine', '0004_auto_20190726_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtag',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
