# Generated by Django 2.2.3 on 2019-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_lab_engine', '0006_auto_20190801_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='file',
            field=models.FileField(default=' ', upload_to='z_lab_engine/static/images'),
        ),
    ]
