# Generated by Django 2.2.3 on 2019-08-06 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_lab_engine', '0007_hash_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hash',
            name='file',
        ),
        migrations.AlterField(
            model_name='hash',
            name='md5',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.MinLengthValidator(32, 'Enter a value with length 32.')]),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha1',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.MinLengthValidator(40, 'Enter a value with length 40.')]),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.MinLengthValidator(64, 'Enter a value with length 64.')]),
        ),
    ]
