# Generated by Django 2.2.3 on 2019-08-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('z_lab_engine', '0008_auto_20190806_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='files/')),
                ('hashes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_lab_engine.Hash')),
            ],
        ),
    ]
