# Generated by Django 2.2.3 on 2019-08-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('z_lab_engine', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hashes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_lab_engine.Hash')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
