# Generated by Django 2.2.3 on 2019-08-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_lab_engine', '0010_auto_20190819_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='hashes',
        ),
    ]
